### ISSUE TITLE
Can't import resume (cannot read property toUpperCase of undefined)

### ISSUE THREAD

**Issue by Agnostic** [JMPerez/linkedin-to-json-resume#12]
Hola José, I'm trying to import my zip file with your app but I got this in the console when I select the file:

```javascript
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
```
In converter.js, line 121.

```javascript
return proficiency[0].toUpperCase() + proficiency.substr(1);
```

**Comment by JMPerez** [comment]
@Agnostic Do you have any languages added in your LinkedIn profile (e.g English, Spanish...)? At the moment the script takes for granted that this is never empty, but I will modify it to check this.

**Comment by Agnostic** [comment]
Yeah, that was the issue, I had english and I think the script is trying to get the level/fluency as well but it was empty. I guess it can be fixed with a simple validation. Thank you!
