### ISSUE TITLE
[object ErrorEvent] when importing .zip file

### ISSUE THREAD

**Issue by sgiebels** [JMPerez/linkedin-to-json-resume#17]
I have just tested the functionality, by git-cloning to my local webserver, accessing the index.html and uploading a .zip file. However, using your demo site worked without problems.

I`m probably missing some Node.js stuff, but am unable to verify this.
Which version Node.js is a requirement?

What is the correct command to install dependencies, `npm install` ?

**Comment by JMPerez** [comment]
Yes, `npm install` and `npm run build`. Tested on node 6.0.0.
