### ISSUE TITLE
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by sgiebels** [JMPerez/linkedin-to-json-resume#18]
# npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

I assuming this minimatch is referenced somewhere in the linkedin-to-json-resume code. Please tell me it is an `user error` and I should update something.

**Comment by JMPerez** [comment]
Closing this ticket. Running `npm list | grep minimatch` reports that the installed version of minimatch is 3.0.4.
