### ISSUE TITLE
Improperly parsed data fields

### ISSUE THREAD

**Issue by sgiebels** [JMPerez/linkedin-to-json-resume#19]
When using the demo on your website for parsing LinkedIn .zip files, there are a lot of fields parsed incorrectly.

startDate contains <Area>, summary contains <Position> and endDate contains StartDate.
The LinkedIn `Job Description` is completely left out.
I have seen a Pull Request, but I am unable to verify if this solves this issue because of the other issue that is preventing me from running the linkedin-to-json-resume code on my webserver.

Regardless of the issues/bugs, I compliment you (JMPerez) for this software initiative! I hope I will be able to use it soon.

Snippet from resulting JSON with sime data replaced by <...>:
    {
      "company": "<Correct Company Name>",
      "position": "",
      "website": "",
      "startDate": "undefined-<Area>-01",
      "summary": "<Position>",
      "highlights": [],
      "endDate": "undefined-<StartDate>-01"
    },
    {

**Comment by JMPerez** [comment]
This should be fixed by #16. Feel free to reopen otherwise.
