### ISSUE TITLE
"location" data not parsed.

### ISSUE THREAD

**Issue by sgiebels** [JMPerez/linkedin-to-json-resume#21]
Eindhoven, North Brabant Province, Netherlands
my Profile.csv (inside of the zip file) has the data:

Country
Zip Code
Geo Location

but these are not parsed, as tested using the demo site:

    "location": {
      "address": "",
      "postalCode": "",
      "city": "",
      "countryCode": "",
      "region": ""
    },

Kind regards, and thanks again for your attention.

**Comment by JMPerez** [comment]
@sgirbels would you mind attaching the file to make it easier to debug/fix it?

**Comment by sgiebels** [comment]
Cannot attach file in public forum, but if you could let me know your e-mail address I can e-mail you the zip file (...with a few privacy related files removed)

**Comment by sgiebels** [comment]
I have not heard back from you after my last message. Is there a way I can send it to you and not make it public?

**Comment by JMPerez** [comment]
@sgiebels I sent you an invite for a private GitHub repo where you can upload the file.

**Comment by sgiebels** [comment]
Thank you, I uploaded a version with some files removed from the zip (contact e-mail addresses etc, login timestamps/ip`s), as I see that these are not required for converting it to JSON.
