### ISSUE TITLE
empty Json

### ISSUE THREAD

**Issue by lironmo** [JMPerez/linkedin-to-json-resume#46]
Hello,
I am getting empty json - tried both local and on your site.

the data is personal so I can send it to you if needed

**Comment by lironmo** [comment]
it seems that the entry.filename is without prefix of "/", so all the switch cases failed:
entry.filename.indexOf("/PhoneNumbers.csv") !== -1

**Comment by lironmo** [comment]
I removed the prefix and it works. maybe something in the structure changed or something in the zip library changed (isomorphic-unzip/zip-browser)

**Comment by santiagofn** [comment]
I can confirm that @lironmo fix works.
